name: Cypress Tests

on:
  push:
    branches:
      - main  # Adjust this branch name as needed
  pull_request:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          echo ${CYPRESS_RECORD_KEY}|
          npx cypress run --record --key ${CYPRESS_RECORD_KEY}
